version: '3'
services:
  app:
    image: sobitprasad/todo-app-prod:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: always